util.o: util.cpp util.h
sockets.o: sockets.cpp sockets.h
protocol.o: protocol.cpp protocol.h sockets.h
cix.o: cix.cpp util.h protocol.h sockets.h logstream.h
cixd.o: cixd.cpp protocol.h sockets.h logstream.h
